### ISSUE TITLE
Auto-configuration via bluetooth

### ISSUE THREAD

**Issue by josephnoir** [watr-li/nodes#2]
Perhaps bluetooth offers the possibility to reduce the necessary configuration when introducing new devices to the network.

**Comment by Lotterleben** [comment]
Hmm, how would bluetooth help with that? (i.e. whats the benefit that makes extra complexity & hardware worthwile, instead of doing it via 802.15.4 and CoAP?)

**Comment by josephnoir** [comment]
I guess you are right. Bluetooth is on the same layer as 802.15.4. I was seduced by the seamless way the bluetooth devices I use connect with my laptop / phone.
